# Generated by Django 5.0.6 on 2024-07-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0002_delete_agregado_remove_cafetam_codcafe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('f_nac', models.DateField(null=True)),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
