# Generated by Django 5.0.6 on 2024-07-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id2', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre2', models.CharField(max_length=30)),
                ('precio2', models.IntegerField()),
                ('f_registro2', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
